name: Main scripts

on:
  push:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/check_main_script.yaml
      - truckersmp-cli
      - truckersmp_cli/*.py
  pull_request:
    branches:
      - master
      - dev
    paths:
      - .github/workflows/check_main_script.yaml
      - truckersmp-cli
      - truckersmp_cli/*.py

jobs:
  check_by_flake8:
    name: Check main scripts by flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install flake8, flake8-docstrings, and flake8-import-order
        run: pip install flake8 flake8-docstrings flake8-import-order
      - name: Check Python scripts by flake8
        run: flake8 --max-line-length=90 --show-source --statistics truckersmp-cli truckersmp_cli/*.py
